### ISSUE TITLE
How to obtain `pairs` information from other non-GPU TDA packages?

### ISSUE THREAD

**Issue by YuchiQiu** [danchern97/RTD_AE#1]
Excellent work! I am wondering if I could use other non-GPU TDA package such as gudhi or giotto instead? 

The critical thing is the variable `pairs=rc['pairs'][dim]` needs to be calculated. I notice the most updated ripser++ no longer has `pairs` in ripserplusplus.run() output rather than the old version you provided in `requirements.txt`. How about other TDA packages? Will the equivalent `pairs` information be available?

Thank you.

**Comment by danchern97** [comment]
Hi! Sorry for the late reply. `RTDLoss` object has a parameter called "engine", which can be switched to Giotto to use it. However, I recommend using our patched version of the Ripser++ (ripserplusplus@git+https://github.com/ArGintum/RipserZeros.git@bac8a96f56e9e3ed46202323accbeeee11c4b54c), which outputs pairs. It is mentioned in requirements.txt

**Comment by needylove** [comment]
Hi, it seems the old version of Ripser++, which you provided in requirements.txt , is no longer available, and the most updated ripser++ no longer has 'pairs'. 
The Giotto also does not have 'pairs' output, do you have any suggestion to solve this problem

Thanks.
